{% set name = "xmlhelpy" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/iam-cms/workflows/xmlhelpy/-/archive/v{{ version }}/xmlhelpy-v{{ version }}.tar.gz
  sha256: 3b46f9f08c029eb2e516e837a60179f112508a0cb72f5b64d63de217acf32fa3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=8.0.0,<9.0.0
    - lxml >=5.0.0,<6.0.0

test:
  imports:
    - xmlhelpy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://gitlab.com/iam-cms/workflows/xmlhelpy
  summary: 'CLI wrapper supporting the xmlhelp interface.'
  description: |
    xmlhelpy is a wrapper library based on Click. Its main goal is to easily provide
    the xmlhelp interface to any Python CLI tool. This interface can be used to
    obtain a machine readable XML representation of tools and their parameters. The
    XML representation can be used, for example, to generate GUIs on top of any
    tool that provides it.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
